# Generated by Django 5.2.14 on 2026-05-14 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('delivered_time', models.DateTimeField(null=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('media', 'Media')], default='text', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('replied_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.threadmessage')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('profile_image', models.URLField(blank=True)),
                ('kind', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('channel', 'Channel'), ('private', 'Private')], default='direct', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkMessage',
            fields=[
                ('threadmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.threadmessage')),
                ('link', models.URLField()),
                ('platform', models.CharField(choices=[('youtube', 'Youtube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('web', 'Web')], default='web', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('chat.threadmessage',),
        ),
        migrations.CreateModel(
            name='MediaMessage',
            fields=[
                ('threadmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.threadmessage')),
                ('media_url', models.URLField()),
                ('media_kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='image', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('chat.threadmessage',),
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('threadmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.threadmessage')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('chat.threadmessage',),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_last_message', to='chat.threadmessage'),
        ),
        migrations.AddField(
            model_name='thread',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ThreadMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_member', to='accounts.profile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.thread')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['member'],
            },
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread'], name='chat_thread_thread__77432d_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['name'], name='chat_thread_name_4695de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadmember',
            unique_together={('member', 'thread')},
        ),
    ]
