# Generated by Django 5.2.14 on 2026-05-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereceipt',
            name='received_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagereceipt',
            name='seen_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
